# Generated by Django 5.2.5 on 2025-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending_product',
            field=models.BooleanField(default=False),
        ),
    ]
